name = "NoLimits"
uuid = "1d491b74-35a5-408f-ae19-cf8524c3769d"
version = "0.1.0"
authors = ["Manuel Huth", "Jonas Arruda", "Clemens Peiter", "Nina Schmid", "Jan Hasenauer"]

[deps]
AdvancedVI = "b5ca4192-6429-45e5-a2d9-87aec30a685c"
Bijectors = "76274a88-744f-5084-9051-94815aaf08c4"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataInterpolations = "82cc6244-b520-54b8-b5a6-8a565e85f1d0"
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
DifferentiationInterface = "a0c0ee7d-e4b9-4e03-894e-1c5f64a51d63"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DynamicPPL = "366bfd00-2699-11ea-058f-f148b4cae6d8"
ExponentialAction = "e24c0720-ea99-47e8-929e-571b494574d3"
FiniteDifferences = "26cc04aa-876d-5657-8c51-4c34ba976000"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
FunctionChains = "8e6b2b91-af83-483e-ba35-d00930e4cf9b"
Functors = "d9f16b24-f501-4c13-a1f2-28368ffc5196"
KernelDensity = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
Latexify = "23fbe1c1-3f47-55db-b15f-69d7ec21a316"
LikelihoodProfiler = "93acb638-a083-5915-8dce-d129bc6a3f59"
LineSearches = "d3d80556-e9d4-5f37-9878-2ab0fcc64255"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
MCMCChains = "c7f686f2-ff18-58e9-bc7b-31028e88f75d"
Measures = "442fdcdd-2543-5da2-b0f3-8c86c306513e"
NormalizingFlows = "50e4474d-9f12-44b7-af7a-91ab30ff6256"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationBBO = "3e6eede4-6085-4f62-9a71-46d9bc1eb92b"
OptimizationOptimJL = "36348300-93cb-4f02-beb5-3c3902f8871e"
OptimizationOptimisers = "42dfb2eb-d2b4-4451-abcd-913932933ac1"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
RDatasets = "ce6b1742-4840-55fa-b093-852dadbb1d8b"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ReverseDiff = "37e2e3b7-166d-5795-8a7a-e32c996b4267"
RuntimeGeneratedFunctions = "7e49a35a-f44a-4d26-94aa-eba1b4ca6b47"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
SciMLSensitivity = "1ed8b502-d754-442c-8d5d-10ac956f44a1"
SciMLStructures = "53ae85a6-f571-4167-b2af-e1d143709226"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
AdvancedVI = "0.6.2"
Bijectors = "0.15.15"
CSV = "0.10.15"
ColorSchemes = "3.31.0"
DataFrames = "1.8.1"
DiffEqBase = "6.199.0"
DiffEqCallbacks = "4.12.0"
Distributed = "1.11.0"
Distributions = "0.25.123"
Documenter = "1.16.1"
DynamicPPL = "0.39.12"
ExponentialAction = "0.2.10"
FiniteDifferences = "0.12.33"
FunctionChains = "0.2.3"
Functors = "0.5"
KernelDensity = "0.6.11"
Latexify = "0.16.10"
LikelihoodProfiler = "0.3.3"
LineSearches = "7.6.0"
Lux = "1.29.4"
MCMCChains = "7.7.0"
Measures = "0.3.3"
Optimisers = "0.4.7"
Optimization = "5.4.0"
OptimizationBBO = "0.4.5"
OptimizationOptimJL = "0.4.9"
OptimizationOptimisers = "0.3.15"
Parameters = "0.12.3"
Plots = "1.41.4"
ProgressMeter = "1.11.0"
RDatasets = "0.8.1"
SciMLBase = "2.134.0"
SpecialFunctions = "2.6.1"
Statistics = "1.11.1"
StatsFuns = "1.5.2"
StatsPlots = "0.15.8"
Test = "1.11.0"
Turing = "0.42.5"
julia = "1.12"
